# Choose source type: "s3" or "local"
source: "s3"

# Path for input files:
#   - If "local": Provide a directory path (e.g., "/data/input/")
#   - If "s3": Provide "bucket-name/prefix/"
input_path: "my-bucket/data/"

# Columns (in CSV order)
columns: ["id", "name", "value"]

# Key column(s) used for updating existing records
keys: ["id"]

# File delimiter (e.g., comma ",", pipe "|", tab "\t") for input files
input_delimiter: ","

# Output settings
output:
  type: "s3"  # "local" or "s3"
  path: "my-bucket/output/final_result.csv"  # File path or S3 key
  format: "csv"  # "csv" or "parquet"
  delimiter: "|"  # Output delimiter (e.g., ",", "|", "\t")